baseurl = "https://chinalifetravel.com/"
defaultContentLanguage = "en"
#languageCode = "zh-Hans"
title = "Hǎo Life In China～"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
 [services.googleAnalytics]
 ID = "G-6GGEM4MNTQ"
 
[params]
 #zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "Hǎo Life In China"
description = "Expat & foreigner life guide in China.～"
avatar = "img/author.jpg"
headerTitle = "Hǎo Life In China～"
motto = "Your friendly guide to living, traveling, and thriving in China."
 footerBottomText = "Your Happy Guide to Life in China，外籍朋友的在华生活指南，记录中国日常。"

# rss = true

[markup]
[markup.goldmark.parser.attribute]
 block = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "qnwlpay@foxmail.com"

siteStartYear = 2025

 favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
 reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
 collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
 showPrevNextPost = true
 reorderShares = ["x", "whatsapp"]

[params.navItems]

#series = { href = "/series", icon = "planet", title = "Series" }
#github = { href = "https://github.com/g1eny0ung", target = "_blank", icon = "logo-github", title = "GitHub" }

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

 [params.advanced]
 customCSS = ["css/custom.css"]
# customJS = []

 [params.experimental]
 jsDate = true
 jsDateFormat = "yyyy年MM月dd日"